language: C
sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    packages:
      - libacl1-dev
      - libbz2-dev
      - liblzma-dev
      - libzip-dev
      - lzop
      - ghostscript
      - groff
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - BUILD_SYSTEM=cmake
  - BUILD_SYSTEM=autotools
matrix:
  exclude:
    - os: osx
      compiler: gcc
before_install:
  - if [ `uname` = "Darwin" ]; then brew update; fi
install:
  - if [ `uname` = "Darwin" ]; then brew install xz lzop lz4; fi
script:
  - build/ci_build.sh

jobs:
  include:
    - stage: makerelease
      os: linux
      compiler: gcc
      env: BUILD_SYSTEM=cmake
      script:
        - build/makerelease.sh
        # wildcard copy to allow us to move versioning forward without updating travis
        - cp -v libarchive-*.tar.gz .versity/SOURCES/
        - (cd .versity; docker build -t versity/libarchive-build .)
        - (cd .versity; bash ./build_rpm_in_docker.sh)
